#!/bin/bash

# PATH
# $HOME/.i3/scripts/volume.sh

sink=$(pacmd list-sinks |awk '/* index:/{print $3}')

up() {
  pactl set-sink-volume $sink +5%
}

down() {
  pactl set-sink-volume $sink -5%
}

mute() {
  pactl set-sink-mute $sink toggle
}

if [[ $1 ]]; then
  case $1 in
      "down") down ;;
      "mute") mute ;;
      "up") up ;;
  esac
elif [[ $BLOCK_BUTTON ]]; then
  # 1 - left click
  # 2 - middle click
  # 3 - right click
  # 4 - scroll up
  # 5 - scroll down
  case $BLOCK_BUTTON in
      1) XDG_CURRENT_DESKTOP=GNOME gnome-control-center sound ;;
      2) mute ;;
      4) up ;;
      5) down ;;
  esac
fi

status=$(amixer sget Master | grep 'Right:' | sed 's/.*\[\([^]]*\)\].*/\1/g')

if [ $status == "off" ]; then
  echo "🔇 ·········· "
else
  amixerresult=$(amixer sget Master | grep 'Right:' | awk -F'[][%]' '{ print $2 }')
  amixerresult=$(expr $amixerresult / 10)

  if [ $amixerresult -le 3 ]; then
    result=" "
  elif [ $amixerresult -le 7 ]; then
    result=" "
  else
    result=" "
  fi

  for i in `seq 1 10`; do
    if [ $i -le $amixerresult ]; then
      result="$result|"
    else
      result="$result·"
    fi
  done

  echo "$result "
fi
